/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;

/**
 *
 * @author amaan
 */
public class UserJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserJFrame.class.getName());

    /**
     * Creates new form UserJFrame
     */
    public UserJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        phoneLabel = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        phoneNumberFormattedTextField = new javax.swing.JFormattedTextField();
        continentLabel = new javax.swing.JLabel();
        continentComboBox = new javax.swing.JComboBox<>();
        experienceLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        experienceTextArea = new javax.swing.JTextArea();
        photoLabel = new javax.swing.JLabel();
        photoPathTextField = new javax.swing.JTextField();
        firstNameLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        ageLabel = new javax.swing.JLabel();
        ageSpinner = new javax.swing.JSpinner();
        genderLabel = new javax.swing.JLabel();
        maleRadioButton = new javax.swing.JRadioButton();
        photoUploadButton = new javax.swing.JButton();
        femaleRadioButton = new javax.swing.JRadioButton();
        photoPreviewLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        phoneLabel.setText("Phone:");

        submitButton.setText("Submit");
        submitButton.addActionListener(this::submitButtonActionPerformed);

        phoneNumberFormattedTextField.setText("   -   -    ");
        phoneNumberFormattedTextField.setToolTipText("123-456-7890");
        phoneNumberFormattedTextField.setCaretPosition(0);
        phoneNumberFormattedTextField.addActionListener(this::phoneNumberFormattedTextFieldActionPerformed);

        continentLabel.setText("Continent:");

        continentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Africa", "Antarctica", "Asia", "Europe", "North America", "South America", "Australia" }));

        experienceLabel.setText("Experience:");

        experienceTextArea.setColumns(20);
        experienceTextArea.setRows(5);
        jScrollPane1.setViewportView(experienceTextArea);

        photoLabel.setText("Photo:");

        firstNameLabel.setText("First Name:");

        lastNameLabel.setText("Last Name:");

        ageLabel.setText("Age:");

        genderLabel.setText("Gender:");

        maleRadioButton.setText("Male");

        photoUploadButton.setText("Upload Photo");
        photoUploadButton.addActionListener(this::photoUploadButtonActionPerformed);

        femaleRadioButton.setText("Female");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(photoPreviewLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstNameLabel)
                                    .addComponent(lastNameLabel)
                                    .addComponent(ageLabel)
                                    .addComponent(genderLabel)
                                    .addComponent(phoneLabel)
                                    .addComponent(continentLabel)
                                    .addComponent(experienceLabel)
                                    .addComponent(photoLabel))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(femaleRadioButton)
                                        .addComponent(firstNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                        .addComponent(lastNameTextField)
                                        .addComponent(maleRadioButton)
                                        .addComponent(phoneNumberFormattedTextField)
                                        .addComponent(ageSpinner))
                                    .addComponent(continentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(photoPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(photoUploadButton))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLabel)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLabel)
                    .addComponent(ageSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderLabel)
                    .addComponent(maleRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(femaleRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLabel)
                    .addComponent(phoneNumberFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(continentLabel)
                    .addComponent(continentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(experienceLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(photoLabel)
                    .addComponent(photoPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(photoUploadButton))
                .addGap(18, 18, 18)
                .addComponent(photoPreviewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed

        String errorTitle = "Something Went Wrong! Please Try Again.";

        try {
            String firstName    = firstNameTextField.getText();
            String lastName     = lastNameTextField.getText();
            int age             = (int) ageSpinner.getValue();
            String gender       = maleRadioButton.isSelected() ? "Male" : femaleRadioButton.isSelected() ? "Female" : null;
            String phone        = phoneNumberFormattedTextField.getText();
            String continent    = (String) continentComboBox.getSelectedItem();
            String experience   = experienceTextArea.getText();
            String photoPath    = photoPathTextField.getText();

            // Validate first name
            if (firstName == null || firstName.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please Enter Your First Name", errorTitle, ERROR_MESSAGE);
                return;
            }

            // Validate last name
            if (lastName == null || lastName.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please Enter Your Last Name", errorTitle, ERROR_MESSAGE);
                return;
            }

            // Validate phone
            if (!phone.matches("\\d{3}-\\d{3}-\\d{4}")) {
                JOptionPane.showMessageDialog(this, "Please Enter Your Valid Phone Number", errorTitle, ERROR_MESSAGE);
                return;
            }

            // Build student and send to parent
            Student student = new Student();
            student.setName(firstName.trim() + " " + lastName.trim());
            student.setAge(age);
            student.setGender(gender);
            student.setPhone(phone);
            student.setContinent(continent);
            student.setExperience(experience);
            student.setPhotoPath(photoPath);

            String successMessage = "First Name: " + firstName.trim()
            + "\nLast Name: " + lastName.trim()
            + "\nAge: " + age
            + "\nGender: " + (gender == null ? "Not selected" : gender)
            + "\nPhone: " + phone
            + "\nContinent: " + (continent == null ? "Not selected" : continent)
            + "\nExperience: " + (experience == null || experience.trim().isEmpty() ? "None" : experience)
            + "\nPhoto Path: " + (photoPath == null || photoPath.trim().isEmpty() ? "Not uploaded" : photoPath);

            // Build the photo icon (if one was uploaded)
            ImageIcon photoIcon = null;
            if (photoPath != null && !photoPath.trim().isEmpty()) {
                ImageIcon rawIcon = new ImageIcon(photoPath);
                Image scaled = rawIcon.getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH);
                photoIcon = new ImageIcon(scaled);
            }

            JOptionPane.showMessageDialog(
                this,
                successMessage,
                "Success",
                JOptionPane.INFORMATION_MESSAGE,
                photoIcon
            );

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid Age Provided", errorTitle, ERROR_MESSAGE);
        }

    }//GEN-LAST:event_submitButtonActionPerformed

    private void phoneNumberFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberFormattedTextFieldActionPerformed
        String phone = phoneNumberFormattedTextField.getText();
        if (!phone.matches("\\d{3}-\\d{3}-\\d{4}")) {
            JOptionPane.showMessageDialog(this, "Please enter a valid phone number (e.g., 123-456-7890)",
                "Invalid Phone", ERROR_MESSAGE);
            phoneNumberFormattedTextField.requestFocus();
        }
    }//GEN-LAST:event_phoneNumberFormattedTextFieldActionPerformed

    private void photoUploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photoUploadButtonActionPerformed

        JFileChooser chooser = new JFileChooser();
        int result = chooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = chooser.getSelectedFile();
            photoPathTextField.setText(selectedFile.getAbsolutePath());

            // Load and scale image to fit label
            ImageIcon icon = new ImageIcon(selectedFile.getAbsolutePath());
            Image scaledImage = icon.getImage().getScaledInstance(photoPreviewLabel.getWidth(), photoPreviewLabel.getHeight(), Image.SCALE_SMOOTH);
            icon = new ImageIcon(scaledImage);

            photoPreviewLabel.setIcon(icon);
            photoPreviewLabel.setText(""); // remove placeholder text
        }

    }//GEN-LAST:event_photoUploadButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UserJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageLabel;
    private javax.swing.JSpinner ageSpinner;
    private javax.swing.JComboBox<String> continentComboBox;
    private javax.swing.JLabel continentLabel;
    private javax.swing.JLabel experienceLabel;
    private javax.swing.JTextArea experienceTextArea;
    private javax.swing.JRadioButton femaleRadioButton;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JRadioButton maleRadioButton;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JFormattedTextField phoneNumberFormattedTextField;
    private javax.swing.JLabel photoLabel;
    private javax.swing.JTextField photoPathTextField;
    private javax.swing.JLabel photoPreviewLabel;
    private javax.swing.JButton photoUploadButton;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
